[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "launchpad_to_github"
authors = [{name = "Maksim Beliaev", email = "beliaev.m.s@gmail.com"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]


dependencies = [
    "launchpadlib",
    "click",
    "pydantic"
]

# development dependencies
[project.optional-dependencies]
test = [
    "pre-commit"
]

deploy = [
    "flit==3.7.1"
]